import { describe, expect, test } from "bun:test";
import { Database } from "bun:sqlite";
import { ensureControlSchema, ControlError } from "../src/control/store";
import { ensureMgmtSchema } from "../src/manage/schema";
import { createDiscoveredWork } from "../src/manage/store";
import { aliasWork, canonicalWorkId, correctLink, refreshWorkHints, workScope } from "../src/manage/relations";

function fixture(){const db=new Database(":memory:");db.exec("PRAGMA foreign_keys=ON");ensureControlSchema(db);ensureMgmtSchema(db);return db;}
function work(db:Database,key:string){return createDiscoveredWork(db,key,key,1);}
function artifact(db:Database,workId:string,artifactId:string,versionId:string){db.query("INSERT INTO mgmt_artifacts VALUES(?,?,'file',?,?,1)").run(artifactId,workId,artifactId,artifactId);db.query("INSERT INTO mgmt_artifact_versions(version_id,artifact_id,content_kind,content_sha256,snapshot_state,producer,observed_at) VALUES(?,?,'content',?,'reference_only','x',1)").run(versionId,artifactId,versionId);}
function execution(db:Database,workId:string,key:string,repo="/repo",host="local"){key=`${host}:pi:${key}`;db.query("INSERT INTO mgmt_session_binding VALUES(?,?,'origin','e',1)").run(key,workId);db.query("INSERT INTO mgmt_executions(execution_id,work_id,stable_id,writer_id,attempt_no,exec_state,source_coverage,ledger_evidence,agent,cwd,started_at,last_observed_at) VALUES(?,?,?,?,1,'ended_ok','ledger_full',?,'pi',?,1,1)").run(key,workId,key,key,JSON.stringify({repo_root:repo}),repo);return key;}

describe("management relations",()=>{
 test("immutable aliases archive profile only and preserve history",()=>{const db=fixture(),canonical=work(db,"canonical"),alias=work(db,"alias");artifact(db,alias,"a","v");db.query("INSERT INTO mgmt_manifests VALUES('m',?,NULL,NULL,NULL,NULL,NULL,'[]','x',1)").run(alias);db.query("INSERT INTO mgmt_manifest_entries VALUES('m','a','v')").run();db.query("INSERT INTO mgmt_acceptances VALUES('ok',?,'m','accepted','owner','{}',NULL,NULL)").run(alias);db.query("INSERT INTO mgmt_discovery_log(at,stable_id,reason) VALUES(1,'s','old')").run();
  expect(aliasWork(db,alias,canonical,{actor:"owner",reason:"duplicate",now:9})).toEqual({alias_work_id:alias,canonical_work_id:canonical,archived:true});
  expect(canonicalWorkId(db,alias)).toBe(canonical);expect(workScope(db,alias)).toEqual([canonical,alias]);
  expect(db.query("SELECT track_state,archive_reason FROM mgmt_work_profile WHERE work_id=?").get(alias)).toEqual({track_state:"archived",archive_reason:"aliased"});
  expect(db.query("SELECT state FROM control_works WHERE work_id=?").get(alias)).toEqual({state:"candidate"});
  expect(db.query("SELECT count(*) n FROM mgmt_manifest_entries WHERE manifest_id='m'").get()).toEqual({n:1});expect(db.query("SELECT invalidated_at FROM mgmt_acceptances WHERE acceptance_id='ok'").get()).toEqual({invalidated_at:null});
  expect(JSON.parse((db.query("SELECT detail FROM mgmt_discovery_log WHERE reason='work_aliased'").get() as any).detail)).toEqual({alias,canonical,actor:"owner"});
  expect(()=>aliasWork(db,alias,canonical,{actor:"owner",reason:"again",now:10})).toThrow(ControlError);
  const archived=work(db,"archived");db.query("UPDATE mgmt_work_profile SET track_state='archived',archive_reason='idle',archived_at=2 WHERE work_id=?").run(archived);expect(aliasWork(db,archived,canonical,{actor:"owner",reason:"historical duplicate",now:10})).toEqual({alias_work_id:archived,canonical_work_id:canonical,archived:true});
  const third=work(db,"third");expect(()=>aliasWork(db,canonical,third,{actor:"owner",reason:"chain",now:10})).toThrow(ControlError);expect(()=>aliasWork(db,third,alias,{actor:"owner",reason:"reverse",now:10})).toThrow(ControlError);
 });
 test("alias rejects in-flight handoffs without changing either work",()=>{const db=fixture(),canonical=work(db,"canonical"),alias=work(db,"alias");const executionId=execution(db,alias,"e");db.query("INSERT INTO mgmt_handoffs(handoff_id,work_id,source_execution_id,target_agent,state,packet,packet_sha256,workspace_fp,isolate) VALUES('h',?,?,'pi','bound','{}','s','f',0)").run(alias,executionId);expect(()=>aliasWork(db,alias,canonical,{actor:"owner",reason:"duplicate",now:9})).toThrow("inflight_handoff:h:bound");expect(db.query("SELECT track_state FROM mgmt_work_profile WHERE work_id=?").get(alias)).toEqual({track_state:"tracking"});expect(db.query("SELECT count(*) n FROM mgmt_work_alias").get()).toEqual({n:0});});
 test("correction supersedes once and fences scanner evidence atomically",()=>{const db=fixture(),w=work(db,"w");const executionId=execution(db,w,"e");artifact(db,w,"a","v1");artifact(db,w,"b","v2");db.query("INSERT INTO mgmt_links(link_id,work_id,subject,relation,object,confidence,evidence_ref,observed_at) VALUES('old',?,?,'modified','v1','strong','jsonl:p#1',1)").run(w,executionId);const result=correctLink(db,"old",{relation:"created",object_id:"v2",actor:"owner",reason:"wrong path",now:8}) as any;expect(result.supersedes).toBe("old");expect(db.query("SELECT superseded_at FROM mgmt_links WHERE link_id='old'").get()).toEqual({superseded_at:8});expect(db.query("SELECT relation,object,supersedes,actor,reason FROM mgmt_links WHERE link_id=?").get(result.link_id)).toEqual({relation:"created",object:"v2",supersedes:"old",actor:"owner",reason:"wrong path"});expect(db.query("SELECT actor,reason FROM mgmt_corrections WHERE evidence_ref='jsonl:p#1'").get()).toEqual({actor:"owner",reason:"wrong path"});expect(()=>correctLink(db,"old",{relation:"read",actor:"owner",reason:"again",now:9})).toThrow(ControlError);});
 test("workspace correction permits non-execution subject but validates artifact scope",()=>{const db=fixture(),w=work(db,"w"),other=work(db,"other");artifact(db,w,"a","v");artifact(db,other,"x","z");db.query("INSERT INTO mgmt_links(link_id,work_id,subject,relation,object,confidence,evidence_ref,observed_at) VALUES('old',?,'workspace:/r','present_in_workspace','v','uncertain','scan:1',1)").run(w);expect(correctLink(db,"old",{relation:"present_in_workspace",object_id:"a",actor:"owner",reason:"current file",now:2})).toMatchObject({subject:w,object:"a",confidence:"uncertain"});db.query("INSERT INTO mgmt_links(link_id,work_id,subject,relation,object,confidence,evidence_ref,observed_at) VALUES('foreign',?,'workspace:/r','present_in_workspace','v','uncertain','scan:2',1)").run(w);expect(()=>correctLink(db,"foreign",{relation:"present_in_workspace",object_id:"z",actor:"owner",reason:"wrong",now:3})).toThrow("object does not belong to work scope");db.query("INSERT INTO mgmt_links(link_id,work_id,subject,relation,object,confidence,evidence_ref,observed_at) VALUES('workspace-read',?,'workspace:/r','present_in_workspace','v','uncertain','scan:3',1)").run(w);expect(()=>correctLink(db,"workspace-read",{relation:"read",actor:"owner",reason:"need execution",now:4})).toThrow("execution not found");expect(()=>correctLink(db,"workspace-read",{relation:"invented",actor:"owner",reason:"invalid",now:4})).toThrow("invalid relation");});
 test("hints are deterministic same-repo facts without attention",()=>{const db=fixture(),a=work(db,"a"),b=work(db,"b"),c=work(db,"c"),remote=work(db,"remote");execution(db,a,"ea","/r");execution(db,b,"eb","/r");execution(db,c,"ec","/other");execution(db,remote,"er","/r","ssh");refreshWorkHints(db,a,7);refreshWorkHints(db,a,8);expect(db.query("SELECT work_id,other_work_id,reason,score,created_at FROM mgmt_work_hints").all()).toEqual([{work_id:a,other_work_id:b,reason:"same_repo",score:0.5,created_at:8}]);expect(db.query("SELECT count(*) n FROM control_attention").get()).toEqual({n:0});});
});
