import { describe, expect, test } from "bun:test";
import { Database } from "bun:sqlite";
import { readFileSync } from "node:fs";
import { ensureControlSchema } from "../src/control/store";
import { createHandoff, checkHandoffPreconditions } from "../src/manage/handoff";
import { launchHandoff, handoffCommand, sshLaunchExecutor } from "../src/manage/launch";
import { ensureMgmtSchema } from "../src/manage/schema";
import type { SourceFs, SourceHost } from "../src/manage/source";

function fixture(coverage="ledger_full",state="done"){
 const db=new Database(":memory:");ensureControlSchema(db);ensureMgmtSchema(db);const ledger=new Database(":memory:");ledger.exec(readFileSync(new URL("../src/ingest/schema.sql",import.meta.url),"utf8"));
 db.query("INSERT INTO control_works VALUES (?,?,?,?,?,?,?,?,?)").run("w","work","test","w","active",0,null,1,1);db.query("INSERT INTO mgmt_work_profile(work_id,origin_mode,closeout_owner,track_state,decision_owner,discovered_title,updated_at) VALUES ('w','discovered','mgmt','tracking','human','work',1)").run();db.query("INSERT INTO mgmt_session_binding VALUES ('configured:claude:s','w','origin','seed',1)").run();db.query("INSERT INTO mgmt_executions(execution_id,work_id,stable_id,writer_id,attempt_no,exec_state,source_coverage,ledger_evidence,started_at,cwd,last_observed_at,agent) VALUES ('e','w','configured:claude:s','wr',1,'running',?,'{}',1,'/repo',?,'claude')").run(coverage,Date.now());ledger.query("INSERT INTO sessions(stable_id,host,runtime,session,origin,cwd,first_seen_at) VALUES ('configured:claude:s','configured','claude','s','human','/repo',1)").run();ledger.query("INSERT INTO current(stable_id,writer_id,state,origin,last_event_at) VALUES ('configured:claude:s','wr',?,'human',?)").run(state,Date.now());return {db,ledger};
}
function source(host:SourceHost,handler:(cwd:string,argv:string[])=>{code:number;stdout:string;stderr:string}):SourceFs{return {host,listFiles:async()=>[],readRange:async()=>null,readFile:async()=>null,exec:async(cwd,argv)=>handler(cwd,argv)};}
const ok=(stdout="")=>({code:0,stdout,stderr:""});

describe("remote management handoff",()=>{
 test("configured host identity routes executor independently of ssh alias and transfers packet",async()=>{const {db,ledger}=fixture();const h=createHandoff(db,ledger,"w",{target_agent:"claude",target_host:"remote-proof",isolate:false});const calls:{cwd:string;argv:string[]}[]=[];const fs=source({host:"remote-proof",kind:"ssh",remote:"koda-dev"},(cwd,argv)=>{calls.push({cwd,argv});return argv[0]==="uname"?ok("Darwin\n"):ok();});let launched:any;const result=await launchHandoff(db,h.handoff_id,{confirmed:true,source:fs,executor:async r=>(launched=r,{receipt:"ssh:remote-proof:42"})});expect(result.state).toBe("launching");expect(launched.host).toEqual({host:"remote-proof",kind:"ssh",remote:"koda-dev"});expect(launched.cwd).toBe("/repo");expect(launched.argv[0]).toBe("claude");expect(launched.argv).not.toContain("--cwd");expect(launched.env.OVERLOAD_PARENT).toBe(`mgmt:handoff:${h.handoff_id}`);expect(calls.some(c=>c.argv[0]==="sh"&&c.argv.includes("/repo/.overload/handoff-"+h.handoff_id+".json"))).toBe(true);});
 test("file_only rejects same workspace and requires matching human actor for isolation",()=>{const {db,ledger}=fixture("file_only","idle");expect(checkHandoffPreconditions(db,ledger,"w")).toMatchObject({cause:"liveness_unknown",allowed:["isolate_with_confirmation"],evidence:{cause:"file_only"}});expect(()=>createHandoff(db,ledger,"w",{target_agent:"claude",target_host:"remote-proof",isolate:false})).toThrow("liveness_unknown");expect(()=>createHandoff(db,ledger,"w",{target_agent:"claude",target_host:"remote-proof",isolate:true,override_reason:"risk",override_actor:"other"})).toThrow("confirmation_required");const h=createHandoff(db,ledger,"w",{target_agent:"claude",target_host:"remote-proof",isolate:true,override_reason:"risk",override_actor:"human"});expect(h.packet).toMatchObject({workspace:{cwd:"/repo",host:"configured"},risk:"原执行可能仍在原目录运行",gaps:[{kind:"liveness_unknown",cause:"file_only",executions:["e"]}]});});
 test("contention enumerates paths and executions and requires isolation",()=>{const {db,ledger}=fixture();db.query("INSERT INTO mgmt_artifacts VALUES ('a','w','file','x','src/x.ts',1)").run();db.query("INSERT INTO mgmt_artifact_versions(version_id,artifact_id,content_kind,content_sha256,snapshot_state,producer,observed_at) VALUES ('v','a','content','x','reference_only','multiple',1)").run();db.query("INSERT INTO mgmt_links(link_id,work_id,subject,relation,object,confidence,evidence_ref,observed_at) VALUES ('l','w','e2','modified','v','uncertain','ev',1)").run();expect(checkHandoffPreconditions(db,ledger,"w")).toMatchObject({cause:"contention",evidence:{paths:["src/x.ts"],executions:["e2"]}});expect(()=>createHandoff(db,ledger,"w",{target_agent:"pi",target_host:"remote-proof",isolate:false})).toThrow("contention");});
 test("failed remote dirty patch never spawns or falls back to source cwd",async()=>{const {db,ledger}=fixture();const h=createHandoff(db,ledger,"w",{target_agent:"pi",target_host:"remote-proof",isolate:true});let spawned=false;const fs=source({host:"remote-proof",kind:"ssh",remote:"koda-dev"},(_cwd,argv)=>{if(argv.join(" ").includes("rev-parse --show-toplevel"))return ok("/repo\n");if(argv.join(" ").includes("rev-parse HEAD"))return ok("abc\n");if(argv.join(" ").includes("rev-parse --git-path"))return ok("/repo/.git/overload/h.patch\n");if(argv.join(" ").includes("rev-parse --git-common-dir"))return ok("/repo/.git\n");if(argv.join(" ").includes("diff --binary"))return ok("patch");if(argv.join(" ").includes("worktree list"))return ok();if(argv.join(" ").includes("worktree add"))return ok();if(argv[0]==="uname")return ok("Darwin\n");if(argv.join(" ").includes("git apply"))return {code:1,stdout:"",stderr:"conflict"};return ok();});const result=await launchHandoff(db,h.handoff_id,{confirmed:true,source:fs,executor:async()=>{spawned=true;return {receipt:"bad"};}});expect(result).toMatchObject({state:"ready_to_launch",outcome:"failed_no_effect"});expect(spawned).toBe(false);});
 test("unknown launch is durable and cannot duplicate",async()=>{const {db,ledger}=fixture();const h=createHandoff(db,ledger,"w",{target_agent:"omp",target_host:"remote-proof",isolate:false});const fs=source({host:"remote-proof",kind:"ssh",remote:"koda-dev"},(_cwd,argv)=>argv[0]==="uname"?ok("Darwin\n"):ok());const result=await launchHandoff(db,h.handoff_id,{confirmed:true,source:fs,executor:async request=>{expect(db.query("SELECT state FROM mgmt_handoff_launch_attempts WHERE idempotency_key=?").get(request.idempotencyKey)).toEqual({state:"requested"});throw new Error("receipt lost");}});expect(result.state).toBe("launch_unknown");await expect(launchHandoff(db,h.handoff_id,{confirmed:true,source:fs,executor:async()=>({receipt:"duplicate"})})).rejects.toMatchObject({code:"conflict"});expect(db.query("SELECT count(*) n FROM mgmt_handoff_launch_attempts WHERE handoff_id=?").get(h.handoff_id)).toEqual({n:1});});
 test("ssh executor uses configured alias, login shell cwd, and parent without Claude cwd flag",async()=>{const old=Bun.spawn;let command:string[]=[];(Bun as any).spawn=(argv:string[])=>{command=argv;return {exited:Promise.resolve(0),stdout:new Blob(["73\n"]).stream(),stderr:new Blob([""]).stream()};};try{const result=await sshLaunchExecutor({handoffId:"h",agent:"claude",cwd:"/tmp/isolated",host:{host:"remote-proof",kind:"ssh",remote:"koda-dev"},argv:["claude","-p","packet"],env:{OVERLOAD_PARENT:"mgmt:handoff:h"},idempotencyKey:"k"});expect(result).toEqual({pid:73,receipt:"ssh:remote-proof:73:/tmp/isolated/.overload/handoff-h.log"});expect(command).toContain("koda-dev");const remote=command.at(-1)!;expect(remote).toContain("/bin/zsh -lic");expect(remote).toContain("/tmp/isolated");expect(remote).toContain("OVERLOAD_PARENT");expect(remote).not.toContain("--cwd");}finally{(Bun as any).spawn=old;}});

 test("supported commands carry real packet without invalid Claude cwd flag",()=>{expect(handoffCommand("pi","/target","/target/.overload/h.json","w")).toContain("@/target/.overload/h.json");expect(handoffCommand("omp","/target","/target/.overload/h.json","w")).toContain("@/target/.overload/h.json");const claude=handoffCommand("claude","/target","/target/.overload/h.json","w");expect(claude).not.toContain("--cwd");expect(claude.join(" ")).toContain("Handoff-Packet: /target/.overload/h.json");});
});
