import {describe,expect,test} from "bun:test";
import {Database} from "bun:sqlite";
import {readFileSync} from "node:fs";
import {ensureControlSchema} from "../src/control/store";
import {createDiscoveredWork,bindExecution} from "../src/manage/store";
import {deriveCloseoutAndArchive} from "../src/manage/archive";

function fixture(opts:{coverage?:string;state?:string;observed?:number;ledger?:boolean}={}){const db=new Database(":memory:");ensureControlSchema(db);const work=createDiscoveredWork(db,"local:pi:x","x",1);bindExecution(db,{workId:work,stableId:"local:pi:x",writerId:"wr",agent:"pi",cwd:null,coverage:opts.coverage??"ledger_full",state:"running",startedAt:1,observedAt:opts.observed??1,evidence:{}});let ledger:Database|null=null;if(opts.ledger!==false){ledger=new Database(":memory:");ledger.exec(readFileSync(new URL("../src/ingest/schema.sql",import.meta.url),"utf8"));ledger.query("INSERT INTO sessions(stable_id,host,runtime,session,origin,cwd,first_seen_at) VALUES ('local:pi:x','local','pi','x','human','/tmp',1)").run();ledger.query("INSERT INTO current(stable_id,writer_id,state,origin,last_event_at) VALUES ('local:pi:x','wr',?,'human',?)").run(opts.state??"done",opts.observed??1);}return {db,ledger,work};}
const profile=(db:Database)=>db.query("SELECT track_state FROM mgmt_work_profile").get();
describe("management archive",()=>{
 test("session_ended ledger state derives closeout then archives after grace without rewriting control state",()=>{const {db,ledger}=fixture({state:"ended",observed:10});expect(deriveCloseoutAndArchive(db,ledger,{now:20,archiveGraceMs:10})).toEqual({ended:1,archived:0});expect(db.query("SELECT exec_state FROM mgmt_executions").get()).toEqual({exec_state:"ended_ok"});expect(deriveCloseoutAndArchive(db,ledger,{now:30,archiveGraceMs:10})).toEqual({ended:0,archived:1});expect(profile(db)).toEqual({track_state:"archived"});expect(db.query("SELECT state FROM control_works").get()).toEqual({state:"candidate"});});
 test("idle-only execution with dead writer derives ended_ok and archives after grace",()=>{const {db}=fixture({observed:1,ledger:false});expect(deriveCloseoutAndArchive(db,null,{now:100,archiveGraceMs:10})).toEqual({ended:1,archived:0});expect(db.query("SELECT exec_state,closeout_evidence IS NOT NULL evidence FROM mgmt_executions").get()).toEqual({exec_state:"ended_ok",evidence:1});expect(deriveCloseoutAndArchive(db,null,{now:110,archiveGraceMs:10})).toEqual({ended:0,archived:1});});
 test("open management attention blocks archive",()=>{const {db,ledger,work}=fixture({state:"ended",observed:10});db.query(`INSERT INTO control_attention(item_id,work_id,revision,state,effect_state,urgency,conclusion,trigger,impact,options,owner,contract_revision,decision_mode,evidence,created_at,updated_at) VALUES('mgmt:block',?,1,'open','not_started','inbox','c','t','i','[]','owner',0,'human_only','{}',1,1)`).run(work);expect(deriveCloseoutAndArchive(db,ledger,{now:20,archiveGraceMs:10})).toEqual({ended:1,archived:0});expect(profile(db)).toEqual({track_state:"tracking"});});
 test("grace retains recently ended work then archives later",()=>{const {db,ledger}=fixture({state:"ended",observed:95});expect(deriveCloseoutAndArchive(db,ledger,{now:100,archiveGraceMs:30})).toEqual({ended:1,archived:0});expect(profile(db)).toEqual({track_state:"tracking"});expect(deriveCloseoutAndArchive(db,ledger,{now:131,archiveGraceMs:30})).toEqual({ended:0,archived:1});expect(profile(db)).toEqual({track_state:"archived"});});
});
