import {describe,expect,test} from "bun:test";
import {Database} from "bun:sqlite";
import {createHash} from "node:crypto";
import {rm,readFile,stat,mkdtemp} from "node:fs/promises";
import {insertManifest,recordAcceptance,requestAcceptance} from "../src/manage/manifest";
import {collectExecution} from "../src/manage/collect";
import {parseClaudeSession,type SessionRecord} from "../src/manage/readers/types";
import {ensureControlSchema} from "../src/control/store";
import {ensureMgmtSchema} from "../src/manage/schema";
import {bindExecution,createDiscoveredWork} from "../src/manage/store";
import {aliasWork,correctLink} from "../src/manage/relations";
import type {SourceFs} from "../src/manage/source";
const enc=new TextEncoder(),sha=(b:Uint8Array)=>createHash("sha256").update(b).digest("hex"),root="/tmp/overload-attribution-test";
function setup(){const db=new Database(":memory:");ensureControlSchema(db);ensureMgmtSchema(db);const workId=createDiscoveredWork(db,"host:pi:seed","seed",1);return {db,workId};}
function execution(db:Database,workId:string,stableId:string,cwd="/repo"){return bindExecution(db,{workId,stableId,writerId:stableId,agent:"pi",cwd,coverage:"ledger_full",state:"running",startedAt:1,observedAt:1,evidence:{},role:"origin"});}
function record(id:string,events:SessionRecord["toolEvents"],cwd="/repo"):SessionRecord{return {runtime:"pi",sessionUuid:id,cwd,gitBranch:null,startedAt:1,endedAt:null,userMessages:[],toolEvents:events,parseErrors:[],lastLineNo:events.length+1};}
function event(path:string,relation:"read"|"modified"|"created",lineNo:number,at:number,isError=false,succeeded=true){return {at,tool:relation==="read"?"Read":"Write",relation,path,lineNo,isError,succeeded};}
function source(files:Record<string,string|null>,dirty:string[]=[]):SourceFs{return {host:{host:"host",kind:"local"},listFiles:async()=>[],readRange:async()=>null,readFile:async(path,max)=>{const text=files[path];if(text==null)return null;const all=enc.encode(text),bytes=all.slice(0,max);return {bytes,truncated:bytes.length<all.length,sha256:sha(bytes)};},exec:async(cwd,argv)=>{expect(cwd).toBe("/repo");expect(argv.slice(0,3)).toEqual(["git","status","--porcelain=v1"]);return {code:0,stdout:dirty.map(path=>` M ${path}\0`).join(""),stderr:""};}};}
const limits={fileMaxBytes:10000,workMaxBytes:100000,snapshotRoot:root};
describe("artifact attribution",()=>{
 test("concurrent successful writers preserve both links and mark every observed version contended",async()=>{const {db,workId}=setup(),a=execution(db,workId,"host:pi:a"),b=execution(db,workId,"host:pi:b");const fs=source({"/repo/a.ts":"one"});await collectExecution(db,fs,workId,a,"/sessions/a",record("a",[event("/repo/a.ts","modified",2,10)]),limits,20);(fs as any).readFile=async(path:string)=>{const bytes=enc.encode("two");return {bytes,truncated:false,sha256:sha(bytes)}};await collectExecution(db,fs,workId,b,"/sessions/b",record("b",[event("/repo/a.ts","modified",2,20)]),limits,30);expect(db.query("SELECT producer FROM mgmt_artifact_versions ORDER BY evidence_at").all()).toEqual([{producer:"multiple"},{producer:"multiple"}]);expect(new Map((db.query("SELECT subject,confidence FROM mgmt_links WHERE relation='modified'").all() as any[]).map(x=>[x.subject,x.confidence]))).toEqual(new Map([[a,"uncertain"],[b,"uncertain"]]));await rm(root,{recursive:true,force:true});});
 test("failed and result-less writes plus reads never become modified evidence",async()=>{const {db,workId}=setup(),eid=execution(db,workId,"host:pi:a"),fs=source({"/repo/a.ts":"x"});await collectExecution(db,fs,workId,eid,"/sessions/a",record("a",[event("/repo/a.ts","modified",2,10,true,false),event("/repo/a.ts","modified",3,10,false,false),event("/repo/a.ts","read",4,10)]),limits,20);expect(db.query("SELECT relation FROM mgmt_links ORDER BY relation").all()).toEqual([{relation:"attempted_modify"},{relation:"read"}]);expect(db.query("SELECT object FROM mgmt_links WHERE relation='attempted_modify'").get()).toEqual({object:(db.query("SELECT artifact_id FROM mgmt_artifacts WHERE display_path='/repo/a.ts'").get() as any).artifact_id});expect(db.query("SELECT count(*) n FROM mgmt_artifact_versions").get()).toEqual({n:0});});
 test("dirty-only file belongs to canonical Work without execution producer",async()=>{const {db,workId}=setup(),alias=createDiscoveredWork(db,"host:pi:alias","alias",1);aliasWork(db,alias,workId,{actor:"owner",reason:"same",now:2});const eid=execution(db,alias,"host:pi:a"),bindingBefore=db.query("SELECT work_id FROM mgmt_session_binding WHERE stable_id='host:pi:a'").get(),fs=source({"/repo/dirty.ts":"dirty"},["dirty.ts"]);await collectExecution(db,fs,alias,eid,"/sessions/a",record("a",[]),limits,20);expect(db.query("SELECT work_id FROM mgmt_session_binding WHERE stable_id='host:pi:a'").get()).toEqual(bindingBefore);expect(db.query("SELECT work_id,kind FROM mgmt_artifacts").get()).toEqual({work_id:workId,kind:"git_dirty"});expect(db.query("SELECT subject,relation,confidence FROM mgmt_links").get()).toEqual({subject:workId,relation:"present_in_workspace",confidence:"uncertain"});});
 test("capture lag uses tool time and marks stale after sixty seconds",async()=>{const {db,workId}=setup(),eid=execution(db,workId,"host:pi:a"),fs=source({"/repo/a.ts":"x"});await collectExecution(db,fs,workId,eid,"/sessions/a",record("a",[event("/repo/a.ts","modified",2,10)]),limits,60_011);expect(db.query("SELECT evidence_at,observed_at,stale_capture FROM mgmt_artifact_versions").get()).toEqual({evidence_at:10,observed_at:60011,stale_capture:1});});
 test("corrected evidence is fenced from later collection",async()=>{const {db,workId}=setup(),eid=execution(db,workId,"host:pi:a"),fs=source({"/repo/a.ts":"x"});await collectExecution(db,fs,workId,eid,"/sessions/a",record("a",[event("/repo/a.ts","modified",2,10)]),limits,20);const link=(db.query("SELECT link_id FROM mgmt_links").get() as any).link_id;correctLink(db,link,{relation:"read",object_id:(db.query("SELECT artifact_id FROM mgmt_artifacts").get() as any).artifact_id,actor:"owner",reason:"wrong",now:21});await collectExecution(db,fs,workId,eid,"/sessions/a",record("a",[event("/repo/a.ts","modified",2,10)]),limits,30);expect(db.query("SELECT relation,superseded_at FROM mgmt_links ORDER BY observed_at").all()).toEqual([{relation:"modified",superseded_at:21},{relation:"read",superseded_at:null}]);});
});
describe("Claude evidence parsing",()=>{
 test("pending Claude call is emitted once when a later range supplies its result",()=>{const header=JSON.stringify({type:"user",sessionId:"c",cwd:"/repo",message:{role:"user",content:"fix"}}),call=JSON.stringify({type:"assistant",sessionId:"c",cwd:"/repo",message:{role:"assistant",content:[{type:"tool_use",id:"w",name:"Write",input:{file_path:"a.ts"}}]}});const first=parseClaudeSession([header,call])!;expect(first.toolEvents).toHaveLength(1);expect(first.pendingCalls).toHaveLength(1);const result=JSON.stringify({type:"user",sessionId:"c",cwd:"/repo",message:{role:"user",content:[{type:"tool_result",tool_use_id:"w",content:"ok"}]}});const second=parseClaudeSession([header,result],{pendingCalls:first.pendingCalls,lineOffset:1})!;expect(second.toolEvents).toEqual([{...first.toolEvents[0],succeeded:true}]);expect(second.toolEvents[0]!.lineNo).toBe(2);expect(second.pendingCalls).toEqual([]);const waiting=parseClaudeSession([header],{pendingCalls:first.pendingCalls,lineOffset:2})!;expect(waiting.toolEvents).toEqual([]);expect(waiting.pendingCalls).toHaveLength(1);});
  test("only an explicitly successful Claude write is attributable",()=>{const base={sessionId:"c",cwd:"/repo"},lines=[JSON.stringify({...base,type:"user",timestamp:1,message:{role:"user",content:"fix"}}),JSON.stringify({...base,type:"assistant",timestamp:2,message:{role:"assistant",content:[{type:"tool_use",id:"good",name:"Write",input:{file_path:"good.ts"}},{type:"tool_use",id:"bad",name:"Write",input:{file_path:"bad.ts"}},{type:"tool_use",id:"read",name:"Read",input:{file_path:"good.ts"}}]}}),JSON.stringify({...base,type:"user",timestamp:3,message:{role:"user",content:[{type:"tool_result",tool_use_id:"good",content:"ok"},{type:"tool_result",tool_use_id:"bad",is_error:true,content:"failed"},{type:"tool_result",tool_use_id:"read",content:"ok"}]}})];const parsed=parseClaudeSession(lines)!;expect(parsed.toolEvents.map(x=>({relation:x.relation,isError:x.isError,succeeded:x.succeeded}))).toEqual([{relation:"modified",isError:false,succeeded:true},{relation:"modified",isError:true,succeeded:false},{relation:"read",isError:false,succeeded:true}]);});
});


test("captured replacement invalidates acceptance and stores private real bytes",async()=>{
 const {db,workId}=setup(),eid=execution(db,workId,"host:pi:replacement"),snapshotRoot=await mkdtemp("/tmp/overload-private-capture-"),files={"/repo/a.ts":"first"},fs=source(files);
 try{
  await collectExecution(db,fs,workId,eid,"/sessions/replacement",record("a",[event("/repo/a.ts","modified",2,10)]),{...limits,snapshotRoot},20);
  const version=db.query("SELECT * FROM mgmt_artifact_versions").get() as any;
  expect(version.snapshot_state).toBe("stored");expect(version.sensitivity).toBe("none");
  expect(await readFile(version.snapshot_path,"utf8")).toBe("first");expect((await stat(version.snapshot_path)).mode&0o777).toBe(0o600);
  const {manifest_id}=insertManifest(db,{work_id:workId,repo_root:null,git_head:null,git_tree_sha:null,base_ref:null,base_sha:null,verification:[],entries:[{artifact_id:version.artifact_id,version_id:version.version_id}]},"owner",21);
  requestAcceptance(db,manifest_id,22);const accepted=recordAcceptance(db,manifest_id,"accepted","owner",{},23);
  files["/repo/a.ts"]="second";
  await collectExecution(db,fs,workId,eid,"/sessions/replacement",record("a",[event("/repo/a.ts","modified",5,30)]),{...limits,snapshotRoot},40);
  expect(db.query("SELECT invalidated_at FROM mgmt_acceptances WHERE acceptance_id=?").get(accepted.acceptance_id)).toEqual({invalidated_at:40});
 }finally{db.close();await rm(snapshotRoot,{recursive:true,force:true});}
});
