type ToolDefinition={name:string;label:string;description:string;parameters:Record<string,unknown>;execute:(id:string,params:Record<string,unknown>)=>Promise<{content:{type:'text';text:string}[];isError?:boolean}>};
type CoordinatorExtensionApi={registerTool:(tool:ToolDefinition)=>void;setActiveTools:(names:string[])=>void;getAllTools:()=>Array<{name:string}>;on:(event:string,handler:(event:Record<string,unknown>)=>unknown)=>void};
const string={type:'string'};
export default function coordinatorExtension(pi:CoordinatorExtensionApi):void{
 const endpoint=process.env.OVERLOAD_COORDINATOR_ENDPOINT,token=process.env.OVERLOAD_COORDINATOR_TOKEN,workId=process.env.OVERLOAD_COORDINATOR_WORK_ID;
 if(!endpoint||!token||!workId)throw new Error('coordinator_binding_required');
 const definitions=[
  {name:'coordinator_dispatch',description:'Dispatch one bounded child under the operator-approved Work. Use independent scope and observable acceptance. The server validates authority and deduplicates request_id.',properties:{request_id:string,title:string,repo:string,base_ref:string,kind:{type:'string',enum:['ship','scout']},scope:{type:'object'},acceptance:{type:'array',items:string}},required:['request_id','title','repo','kind','scope','acceptance']},
  {name:'coordinator_status',description:'Read persisted child status, attempts and review evidence. Do not poll repeatedly; actionable child transitions wake this session.',properties:{},required:[]},
  {name:'coordinator_review',description:'Record evidence-based acceptance, bounded rework or escalation of a child. Worker self-report alone is not acceptance; supply independently inspected artifact paths and SHA256 hashes.',properties:{task_id:string,attempt_id:string,state:string,verdict:{type:'string',enum:['accept','rework','escalate']},reason:string,evidence:{type:'array',items:{type:'object',properties:{path:string,sha256:string},required:['path','sha256']}}},required:['task_id','attempt_id','state','verdict','reason','evidence']},
  {name:'coordinator_deliver',description:'Request final operator acceptance only after every current child has been reviewed. Never merge, push, archive or declare completion yourself.',properties:{summary:string},required:['summary']}
 ];
 pi.on('session_start',()=>{const allowed=new Set(['read','grep','find','ls',...definitions.map(d=>d.name)]);pi.setActiveTools(pi.getAllTools().filter(tool=>allowed.has(tool.name.toLowerCase())).map(tool=>tool.name));});
 for(const definition of definitions)pi.registerTool({name:definition.name,label:definition.name,description:definition.description,parameters:{type:'object',properties:definition.properties,required:definition.required,additionalProperties:false},async execute(id,params){const response=await fetch(endpoint+'/'+definition.name,{method:'POST',headers:{authorization:'Bearer '+token,'content-type':'application/json'},body:JSON.stringify({...params,work_id:workId,tool_call_id:id}),signal:AbortSignal.timeout(30000)});const text=await response.text();return {content:[{type:'text',text}],...(!response.ok?{isError:true}:{})};}});
 pi.on('before_agent_start',event=>({systemPrompt:String(event.systemPrompt??'')+'\nYou are the delivery owner of the bound Overload Work. Delegate changes through coordinator_dispatch, supervise only actionable events, independently inspect evidence before coordinator_review, and request human final acceptance through coordinator_deliver. Ordinary worker progress must not interrupt the operator. Never use shell or external agents to bypass these tools. Never claim a worker report or a queued request is a verified result.'}));
}
