import {afterEach,expect,test} from "bun:test";import {mkdtempSync,rmSync,writeFileSync} from "node:fs";import {tmpdir} from "node:os";import {join} from "node:path";import {addTask,getTask,openStore,transition} from "./store";import {openAnswersDb,consumeAnswers,requestApproval} from "./approval";import {SpoolWriter} from "./spool";import {runCli} from "./cli";
const dirs:string[]=[];afterEach(()=>{delete process.env.OVERLOAD_ORCHESTRATOR_PATH;delete process.env.OVERLOAD_ANSWERS_PATH;dirs.splice(0).forEach(d=>rmSync(d,{recursive:true,force:true}));});
function fixture(){const root=mkdtempSync(join(tmpdir(),"approval-"));dirs.push(root);writeFileSync(join(root,"host"),"local\n");const db=openStore(join(root,"orch.db")),answers=openAnswersDb(join(root,"answers.db")),spool=new SpoolWriter(db,root),task=addTask(db,"t",root,"a".repeat(40));db.run("UPDATE tasks SET state='running' WHERE task_id=?",task.task_id);transition(db,task.task_id,"runner_exit",{evidence_complete:true},100);return{root,db,answers,spool,task};}
test("valid answer is consumed and transitions",()=>{const f=fixture(),id=requestApproval(f.db,f.spool,f.task.task_id,"ready","Approve?",["approve","reject"]);f.answers.run("INSERT INTO answers VALUES(?,?,?,?)",[id,"approve","cli",200]);consumeAnswers(f.db,f.answers,f.spool,300);expect(getTask(f.db,f.task.task_id)?.state).toBe("submitted");expect((f.db.query("SELECT consumed_at,actor FROM approvals WHERE approval_id=?").get(id) as any).actor).toBe("cli");expect((f.answers.query("SELECT count(*) n FROM answers").get() as any).n).toBe(0);f.spool.close();f.answers.close();f.db.close();});
test("foreign approval is skipped without audit and remains queued",()=>{const f=fixture(),now=Date.now();f.answers.run("INSERT INTO answers VALUES(?,?,?,?)",["request-foreign#tool-call","approve","extension",now]);consumeAnswers(f.db,f.answers,f.spool,now);expect((f.answers.query("SELECT count(*) n FROM answers WHERE approval_id=?").get("request-foreign#tool-call") as {n:number}).n).toBe(1);expect((f.db.query("SELECT count(*) n FROM task_events WHERE event='answer_discarded'").get() as {n:number}).n).toBe(0);f.spool.close();f.answers.close();f.db.close();});
test("expired and invalid-option answers are discarded",()=>{for(const kind of ["expired","invalid_option"]){const f=fixture(),id=requestApproval(f.db,f.spool,f.task.task_id,"ready","Q",["approve"],kind==="expired"?1:100000);const now=kind==="expired"?Date.now()+2:Date.now();f.answers.run("INSERT INTO answers VALUES(?,?,?,?)",[id,kind==="expired"?"approve":"reject","cli",now]);consumeAnswers(f.db,f.answers,f.spool,now);expect((f.db.query("SELECT detail FROM task_events WHERE event='answer_discarded' ORDER BY id DESC").get() as any).detail).toContain(kind);f.spool.close();f.answers.close();f.db.close();}});
test("retention removes foreign rows older than seven days",()=>{const f=fixture(),now=10*24*3600*1000;f.answers.run("INSERT INTO answers VALUES(?,?,?,?)",["request-foreign#old-tool-call","approve","extension",now-7*24*3600*1000-1]);consumeAnswers(f.db,f.answers,f.spool,now);expect((f.answers.query("SELECT count(*) n FROM answers").get() as {n:number}).n).toBe(0);expect(getTask(f.db,f.task.task_id)?.state).toBe("awaiting_human");f.spool.close();f.answers.close();f.db.close();});
test("answer for abandoned task is discarded without throwing",()=>{const f=fixture(),id=requestApproval(f.db,f.spool,f.task.task_id,"ready","Approve?",["approve"]);transition(f.db,f.task.task_id,"human_abandon",{},400);f.answers.run("INSERT INTO answers VALUES(?,?,?,?)",[id,"approve","cli",500]);expect(()=>consumeAnswers(f.db,f.answers,f.spool,600)).not.toThrow();expect((f.answers.query("SELECT count(*) n FROM answers").get() as {n:number}).n).toBe(0);const event=f.db.query("SELECT detail FROM task_events WHERE task_id=? AND event='answer_discarded'").get(f.task.task_id) as {detail:string};expect(JSON.parse(event.detail).reason).toBe("task_not_awaiting");expect((f.db.query("SELECT consumed_at FROM approvals WHERE approval_id=?").get(id) as {consumed_at:number|null}).consumed_at).toBeNull();f.spool.close();f.answers.close();f.db.close();});
test("CLI answer round-trips through mailbox consumer",async()=>{const f=fixture(),id=requestApproval(f.db,f.spool,f.task.task_id,"ready","Q",["approve"]);f.answers.close();process.env.OVERLOAD_ORCHESTRATOR_PATH=join(f.root,"orch.db");process.env.OVERLOAD_ANSWERS_PATH=join(f.root,"answers.db");await runCli(["answer",id,"approve"],()=>{});const answers=openAnswersDb(join(f.root,"answers.db"));consumeAnswers(f.db,answers,f.spool,Date.now());expect(getTask(f.db,f.task.task_id)?.state).toBe("submitted");answers.close();f.spool.close();f.db.close();});
