import { Database } from "bun:sqlite";
import { existsSync, readFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { randomUUID } from "node:crypto";
import type { SpoolWriter } from "./spool";
import { getTask, transition } from "./store";
import { closeTarget, consumeDecision, defaultMailboxPath, getTarget, markReceipt, openMailbox, receipt, registerTarget } from "../decision-bot/mailbox";
import { loadPolicy, policyAuthorizes } from "../decision-bot/policy";

export const defaultAnswersPath=defaultMailboxPath;
export const openAnswersDb=openMailbox;
export function requestApproval(db:Database,spool:SpoolWriter,taskId:string,gate:"ready"|"ci_anomaly",question:string,options:string[],expiresInMs=24*3600*1000,answers=openMailbox()):string{
 const task=getTask(db,taskId);if(!task)throw new Error(`Task not found: ${taskId}`);const existing=db.query("SELECT approval_id FROM approvals WHERE task_id=? AND gate=? AND consumed_at IS NULL").get(taskId,gate) as any;if(existing)return existing.approval_id;
 const approvalId=randomUUID(),now=Date.now(),expires=now+expiresInMs,path=join(homedir(),".overload","artifacts",taskId);db.run("INSERT INTO approvals(approval_id,task_id,gate,question,options,requested_at,expires_at) VALUES(?,?,?,?,?,?,?)",[approvalId,taskId,gate,question,JSON.stringify(options),now,expires]);
 const files=(name:string)=>{const p=join(path,name);return existsSync(p)?readFileSync(p,"utf8"):"";};const evidence={diff:files("diff.patch"),commits:files("commits.txt"),status:files("status.txt"),checks:files("checks.txt"),runner:files("runner.log")};
 const target=registerTarget(answers,{consumerOwner:"orchestrator",approvalId,stableId:task.stable_id??taskId,question,options,effect:gate==="ready"?"push_and_create_pr":"ci_resolution",scope:{gate,taskId,repo:task.repo,base:task.base_ref,branch:task.branch},evidence,expiresAt:expires});
 const summary=`${gate==="ready"?"Changes are ready for your approval.":"CI requires your decision."} Evidence: ${path} (${evidence.checks.trim().split("\n")[0]?.slice(0,160)||"check evidence unavailable"}). Decide within ${Math.ceil(expiresInMs/3600000)}h; without approval the task enters blocked and its worktree is retained.`;spool.emit(task.stable_id??taskId,"decision_requested",{request_id:approvalId,approval_id:approvalId,consumer_owner:"orchestrator",target_version:target.targetVersion,summary,question,options,gate,expires_at:expires,evidence_path:path});return approvalId;
}
function audit(db:Database,taskId:string,event:string,detail:Record<string,unknown>,now:number):void{const task=getTask(db,taskId);db.run("INSERT INTO task_events(task_id,at,from_state,to_state,event,detail) VALUES(?,?,?,?,?,?)",[taskId,now,task?.state??null,task?.state??"unknown",event,JSON.stringify(detail)]);}
export function consumeAnswers(db:Database,answers:Database,spool:SpoolWriter,now=Date.now()):void{
 answers.run("DELETE FROM answers WHERE at < ?",now-7*24*3600*1000);const approvals=db.query("SELECT * FROM approvals WHERE consumed_at IS NULL").all() as any[];
 for(const approval of approvals){let target=getTarget(answers,"orchestrator",approval.approval_id);if(!target){const task=getTask(db,approval.task_id);if(!task)continue;target=registerTarget(answers,{consumerOwner:"orchestrator",approvalId:approval.approval_id,stableId:task.stable_id??task.task_id,question:approval.question,options:JSON.parse(approval.options),effect:approval.gate==="ready"?"push_and_create_pr":"ci_resolution",scope:{gate:approval.gate,taskId:task.task_id,repo:task.repo,base:task.base_ref,branch:task.branch},evidence:{legacy:true},expiresAt:approval.expires_at});if(answers.query("SELECT 1 FROM answers WHERE approval_id=?").get(approval.approval_id))answers.run("INSERT OR IGNORE INTO answer_metadata(approval_id,consumer_owner,provenance) VALUES(?,'orchestrator','legacy-human')",approval.approval_id);}
  let r=receipt(answers,"orchestrator",approval.approval_id);if(!r)r=consumeDecision(answers,{consumerOwner:"orchestrator",approvalId:approval.approval_id,targetVersion:target.targetVersion,policyHash:loadPolicy().hash,now,liveValid:()=>getTask(db,approval.task_id)?.state==="awaiting_human",policyValid:(t,p)=>!!p&&policyAuthorizes(loadPolicy(),t,p.answer,p.policyHash)});if(!r){const pending=answers.query("SELECT answer,actor FROM answers WHERE approval_id=?").get(approval.approval_id) as any;if(pending){const why=now>=approval.expires_at?"expired":!target.options.includes(pending.answer)?"invalid_option":getTask(db,approval.task_id)?.state!=="awaiting_human"?"task_not_awaiting":null;if(why){audit(db,approval.task_id,"answer_discarded",{approval_id:approval.approval_id,reason:why,actor:pending.actor},now);answers.run("DELETE FROM answers WHERE approval_id=?",approval.approval_id);answers.run("DELETE FROM answer_metadata WHERE approval_id=?",approval.approval_id);}}continue;}
  const current=getTask(db,approval.task_id);if(current?.state==="awaiting_human")db.transaction(()=>{transition(db,approval.task_id,`answer=${r!.answer}`,{actor:r!.actor,approval_id:approval.approval_id,receipt_id:r!.receiptId},now);db.run("UPDATE approvals SET consumed_at=?,actor=? WHERE approval_id=? AND consumed_at IS NULL",[now,r!.actor,approval.approval_id]);})();markReceipt(answers,r.receiptId,"applied",now);spool.emit(getTask(db,approval.task_id)?.stable_id??approval.task_id,"decision_resolved",{request_id:approval.approval_id,state:"resolved",selected:r.answer,answer:r.answer,actor:r.actor,receipt_id:r.receiptId});
 }
}
export function expireApprovals(db:Database,now?:number):void;
export function expireApprovals(db:Database,spool:SpoolWriter,now?:number,answers?:Database):void;
export function expireApprovals(db:Database,arg?:number|SpoolWriter,at=Date.now(),answers?:Database):void{const spool=typeof arg==="number"||arg===undefined?undefined:arg;const now=typeof arg==="number"?arg:at;const rows=db.query("SELECT * FROM approvals WHERE consumed_at IS NULL AND expires_at<=?").all(now) as any[];for(const r of rows){if(getTask(db,r.task_id)?.state==="awaiting_human")transition(db,r.task_id,"gate_expire",{approval_id:r.approval_id},now);db.run("UPDATE approvals SET consumed_at=?,actor='expired' WHERE approval_id=?",[now,r.approval_id]);if(answers)closeTarget(answers,"orchestrator",r.approval_id,"expired");spool?.emit(getTask(db,r.task_id)?.stable_id??r.task_id,"decision_resolved",{request_id:r.approval_id,state:"expired"});}}
