import { expect,test } from "bun:test";
import { mkdirSync,mkdtempSync,rmSync,writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { openStore,addTask,transition,getTask } from "./store";
import { openAnswersDb,requestApproval,consumeAnswers,replayAppliedReceipts,reconcileApprovalEffects,expireApprovals } from "./approval";
import { SpoolWriter } from "./spool";
import { registerTarget,writeHumanAnswer,getTarget,receipt,consumeDecision } from "../decision-bot/mailbox";
import { createWork,getAttention } from "../control/store";
test("approval intent is durable before mailbox repair",()=>{const root=mkdtempSync(join(tmpdir(),"approval-intent-"));try{writeFileSync(join(root,"host"),"local\n");const db=openStore(join(root,"o.db")),answers=openAnswersDb(join(root,"a.db")),spool=new SpoolWriter(db,root),task=addTask(db,"t",root,"a".repeat(40));db.run("UPDATE tasks SET state='running' WHERE task_id=?",task.task_id);transition(db,task.task_id,"runner_exit",{evidence_complete:true});const id=requestApproval(db,spool,task.task_id,"confirm_stopped","Stopped?",["approve"],1,answers);expect(db.query("SELECT approval_id FROM approval_intents WHERE approval_id=?").get(id)).toBeTruthy();spool.close();answers.close();db.close();}finally{rmSync(root,{recursive:true,force:true});}});
test("human_only target cannot be bot-consumed",()=>{const root=mkdtempSync(join(tmpdir(),"human-only-"));try{writeFileSync(join(root,"host"),"local\n");const db=openStore(join(root,"o.db")),answers=openAnswersDb(join(root,"a.db")),spool=new SpoolWriter(db,root),task=addTask(db,"t",root,"a".repeat(40));db.run("UPDATE tasks SET state='running' WHERE task_id=?",task.task_id);transition(db,task.task_id,"runner_exit",{evidence_complete:true});const id=requestApproval(db,spool,task.task_id,"keep_held","Keep?",["approve"],1000,answers);const target=getTarget(answers,"orchestrator",id)!;expect(target.decisionMode).toBe("human_only");answers.run("INSERT INTO bot_attempts(attempt_id,bot_id,consumer_owner,approval_id,target_version,owner_token,lease_expires_at,policy_hash,evidence_hash,state,started_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)",["at","bot","orchestrator",id,target.targetVersion,"tok",9e12,"ph",target.evidenceHash,"proposed",1]);answers.run("INSERT INTO bot_proposals(attempt_id,consumer_owner,approval_id,target_version,action,answer,reason,evidence_refs,policy_hash,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)",["at","orchestrator",id,target.targetVersion,"answer","approve","r","[]","ph",1]);consumeAnswers(db,answers,spool,3);expect(getTask(db,task.task_id)?.state).toBe("awaiting_human");expect(receipt(answers,"orchestrator",id)).toBeNull();spool.close();answers.close();db.close();}finally{rmSync(root,{recursive:true,force:true});}});
test("terminal mailbox outcome survives receipt replay",()=>{const root=mkdtempSync(join(tmpdir(),"terminal-replay-"));try{writeFileSync(join(root,"host"),"local\n");const db=openStore(join(root,"o.db")),answers=openAnswersDb(join(root,"a.db")),spool=new SpoolWriter(db,root);answers.run("INSERT INTO decision_receipts(receipt_id,consumer_owner,approval_id,target_version,answer,actor,consumed_at,applied_at,outcome) VALUES(?,?,?,?,?,?,?,?,?)",["r","orchestrator","a","v","approve","ui",1,2,"succeeded"]);db.run("INSERT INTO applied_receipts VALUES(?,?,?,?,?)",["r","t","approve",1,"transitioned"]);replayAppliedReceipts(db,answers,3);expect((answers.query("SELECT outcome FROM decision_receipts WHERE receipt_id='r'").get() as any).outcome).toBe("succeeded");spool.close();answers.close();db.close();}finally{rmSync(root,{recursive:true,force:true});}});
test("receipt projection recovers from durable applied receipt",  ()=>{const root=mkdtempSync(join(tmpdir(),"receipt-recover-"));try{writeFileSync(join(root,"host"),"local\n");const db=openStore(join(root,"o.db")),answers=openAnswersDb(join(root,"a.db")),spool=new SpoolWriter(db,root);answers.run("INSERT INTO decision_receipts(receipt_id,consumer_owner,approval_id,target_version,answer,actor,consumed_at) VALUES(?,?,?,?,?,?,?)",["receipt","orchestrator","approval","v","approve","cli",1]);db.run("INSERT INTO applied_receipts VALUES(?,?,?,?,?)",["receipt", "task","approve",1,"transitioned"]);consumeAnswers(db,answers,spool,2);expect((answers.query("SELECT applied_at FROM decision_receipts WHERE receipt_id=?").get("receipt") as any)?.applied_at).toBe(2);spool.close();answers.close();db.close();}finally{rmSync(root,{recursive:true,force:true});}});
test("human approval moves the held task out of awaiting_human",()=>{const root=mkdtempSync(join(tmpdir(),"human-apply-"));try{writeFileSync(join(root,"host"),"local\n");const db=openStore(join(root,"o.db")),answers=openAnswersDb(join(root,"a.db")),spool=new SpoolWriter(db,root),task=addTask(db,"t",root,"a".repeat(40));db.run("UPDATE tasks SET state='running' WHERE task_id=?",task.task_id);transition(db,task.task_id,"runner_exit",{evidence_complete:true});const id=requestApproval(db,spool,task.task_id,"ready","Approve?",["approve","reject"],1000,answers);expect(writeHumanAnswer(answers,"orchestrator",id,"approve","ui",2).ok).toBe(true);consumeAnswers(db,answers,spool,3);expect(getTask(db,task.task_id)?.state).toBe("submitted");expect(db.query("SELECT receipt_id FROM applied_receipts WHERE task_id=?").all(task.task_id).length).toBe(1);spool.close();answers.close();db.close();}finally{rmSync(root,{recursive:true,force:true});}});
test("a stale approval does not strand later decisions",()=>{const root=mkdtempSync(join(tmpdir(),"stale-approval-"));try{writeFileSync(join(root,"host"),"local\n");const db=openStore(join(root,"o.db")),answers=openAnswersDb(join(root,"a.db")),spool=new SpoolWriter(db,root);const held=(name:string)=>{const repo=join(root,name);mkdirSync(repo,{recursive:true});const t=addTask(db,name,repo,"a".repeat(40));db.run("UPDATE tasks SET state='running' WHERE task_id=?",t.task_id);transition(db,t.task_id,"runner_exit",{evidence_complete:true});return t.task_id;};const stale=held("stale"),live=held("live");const staleId=requestApproval(db,spool,stale,"ready","Approve?",["approve","reject"],1000,answers),liveId=requestApproval(db,spool,live,"ready","Approve?",["approve","reject"],1000,answers);expect(writeHumanAnswer(answers,"orchestrator",staleId,"approve","ui",2).ok).toBe(true);expect(writeHumanAnswer(answers,"orchestrator",liveId,"approve","ui",2).ok).toBe(true);
 // the answer is recorded as a receipt while the task is still held, then the task leaves awaiting_human before the orchestrator applies it
 expect(consumeDecision(answers,{consumerOwner:"orchestrator",approvalId:staleId,targetVersion:getTarget(answers,"orchestrator",staleId)!.targetVersion,policyHash:"ph",now:2,liveValid:()=>true,policyValid:()=>false})).toBeTruthy();
 transition(db,stale,"human_abandon",{},2);consumeAnswers(db,answers,spool,3);expect(getTask(db,live)?.state).toBe("submitted");expect(getTask(db,stale)?.state).toBe("abandoned");expect(receipt(answers,"orchestrator",staleId)?.outcome).toBe("failed");spool.close();answers.close();db.close();}finally{rmSync(root,{recursive:true,force:true});}});
test("a failed effect tells the operator why on the original card",()=>{const root=mkdtempSync(join(tmpdir(),"effect-detail-"));try{writeFileSync(join(root,"host"),"local\n");const db=openStore(join(root,"o.db")),answers=openAnswersDb(join(root,"a.db")),spool=new SpoolWriter(db,root);
 const work=createWork(answers,{title:"w",source:"test",contract:{objective:"o",acceptance:[{id:"check",kind:"check",description:"d"}],non_goals:[],scope:{repo:root},budget:{},stop_conditions:[],decision_owner:"owner"}},1);
 const task=addTask(db,"t",root,"a".repeat(40),1,{workId:work.work_id,contractRevision:work.revision});db.run("UPDATE tasks SET state='running' WHERE task_id=?",task.task_id);transition(db,task.task_id,"runner_exit",{evidence_complete:true});
 const id=requestApproval(db,spool,task.task_id,"ready","Approve?",["approve","reject"],1000,answers);expect(getAttention(answers,`orchestrator:${id}`)?.effect_detail).toBeNull();
 expect(writeHumanAnswer(answers,"orchestrator",id,"approve","ui",2).ok).toBe(true);consumeAnswers(db,answers,spool,3);expect(getTask(db,task.task_id)?.state).toBe("submitted");
 transition(db,task.task_id,"push_fail",{},4);reconcileApprovalEffects(db,answers,5);
 const card=getAttention(answers,`orchestrator:${id}`);expect(card?.effect_state).toBe("failed");expect(card?.effect_detail).toBe("push_failed");
 spool.close();answers.close();db.close();}finally{rmSync(root,{recursive:true,force:true});}});
test("expired predecessor approval cannot release or expire a reopened attempt",()=>{
 const root=mkdtempSync(join(tmpdir(),"approval-reopen-"));
 writeFileSync(join(root,"host"),"local\n");
 const db=openStore(join(root,"o.db")),answers=openAnswersDb(join(root,"a.db")),spool=new SpoolWriter(db,root);
 try{
   const task=addTask(db,"t",root,"a".repeat(40));
   db.run("UPDATE tasks SET state='awaiting_human',attempt_id='old-attempt' WHERE task_id=?",task.task_id);
   const oldId=requestApproval(db,spool,task.task_id,"ready","Old?",["approve","reject"],60000,answers);
   expect(writeHumanAnswer(answers,"orchestrator",oldId,"approve","owner").ok).toBe(true);
   transition(db,task.task_id,"gate_expire",{},Date.now());
   const now=Date.now();transition(db,task.task_id,"human_reopen",{},now);
   transition(db,task.task_id,"spawn_ok",{},now+1);transition(db,task.task_id,"runner_exit",{evidence_complete:true},now+2);
   consumeAnswers(db,answers,spool,now+3);expireApprovals(db,spool,now+3,answers);
   expect(getTask(db,task.task_id)?.state).toBe("awaiting_human");
   expect(receipt(answers,"orchestrator",oldId)).toBeNull();
   expect(getTarget(answers,"orchestrator",oldId)?.state).toBe("closed");
   const newId=requestApproval(db,spool,task.task_id,"ready","New?",["approve","reject"],60000,answers);
   expect(newId).not.toBe(oldId);
   expect(writeHumanAnswer(answers,"orchestrator",newId,"approve","owner",now+4).ok).toBe(true);
   consumeAnswers(db,answers,spool,now+5);
   expect(getTask(db,task.task_id)?.state).toBe("submitted");
 }finally{spool.close();answers.close();db.close();rmSync(root,{recursive:true,force:true});}
});
