import { afterEach, expect, test } from "bun:test";
import { execFileSync } from "node:child_process"; import { mkdtempSync, rmSync, writeFileSync } from "node:fs"; import { tmpdir } from "node:os"; import { join } from "node:path";
import { runCli } from "./cli"; import { addTask, claim, openStore } from "./store";
const dirs:string[]=[];afterEach(()=>{delete process.env.OVERLOAD_ORCHESTRATOR_PATH;dirs.splice(0).forEach(d=>rmSync(d,{recursive:true,force:true}));});
function git(repo:string,...args:string[]):string{return execFileSync("git",["-C",repo,...args],{encoding:"utf8"}).trim();}
function repo(){const d=mkdtempSync(join(tmpdir(),"cli-repo-"));dirs.push(d);git(d,"init","-q");git(d,"config","user.email","a@a.com");git(d,"config","user.name","a");writeFileSync(join(d,"f"),"one");git(d,"add","f");git(d,"commit","-q","-m","one");return d;}
test("add resolves default HEAD to commit SHA",async()=>{const d=mkdtempSync(join(tmpdir(),"cli-")),r=repo();dirs.push(d);process.env.OVERLOAD_ORCHESTRATOR_PATH=join(d,"db");const lines:string[]=[];await runCli(["add","task","--repo",r],x=>lines.push(x));expect(JSON.parse(lines[0]!).base_ref).toBe(git(r,"rev-parse","HEAD"));});
test("add resolves branch base ref to branch SHA",async()=>{const d=mkdtempSync(join(tmpdir(),"cli-")),r=repo();dirs.push(d);process.env.OVERLOAD_ORCHESTRATOR_PATH=join(d,"db");git(r,"branch","feature");const lines:string[]=[];await runCli(["add","task","--repo",r,"--base-ref","feature"],x=>lines.push(x));expect(JSON.parse(lines[0]!).base_ref).toBe(git(r,"rev-parse","feature"));});
test("unresolvable base ref inserts no task",async()=>{const d=mkdtempSync(join(tmpdir(),"cli-")),r=repo();dirs.push(d);process.env.OVERLOAD_ORCHESTRATOR_PATH=join(d,"db");await expect(runCli(["add","task","--repo",r,"--base-ref","missing"],()=>{})).rejects.toThrow("base ref not resolvable: missing");const lines:string[]=[];await runCli(["ls"],x=>lines.push(x));expect(lines).toHaveLength(0);});
test("add ls show advance abandon reopen round trip",async()=>{const d=mkdtempSync(join(tmpdir(),"cli-")),r=repo();dirs.push(d);process.env.OVERLOAD_ORCHESTRATOR_PATH=join(d,"db");let lines:string[]=[];await runCli(["add","task","--repo",r],x=>lines.push(x));const id=JSON.parse(lines[0]!).task_id;lines=[];await runCli(["ls"],x=>lines.push(x));expect(lines[0]).toContain(id);lines=[];await runCli(["show",id],x=>lines.push(x));expect(JSON.parse(lines[0]!).title).toBe("task");let db=openStore();claim(db,"o");db.close();await runCli(["advance",id,"spawn_fail"],()=>{});await runCli(["reopen",id],()=>{});await runCli(["abandon",id],()=>{});lines=[];await runCli(["show",id],x=>lines.push(x));expect(JSON.parse(lines[0]!).state).toBe("abandoned");});
test("gc lists terminal worktrees and only deletes with --apply",async()=>{const d=mkdtempSync(join(tmpdir(),"cli-gc-"));dirs.push(d);process.env.OVERLOAD_ORCHESTRATOR_PATH=join(d,"db");const db=openStore();const task=addTask(db,"t",d,"a".repeat(40));db.run("UPDATE tasks SET state='abandoned',worktree=? WHERE task_id=?",[join(d,"nonexistent-wt"),task.task_id]);db.close();let lines:string[]=[];await runCli(["gc"],x=>lines.push(x));const row=JSON.parse(lines[0]!);expect(row).toEqual({task_id:task.task_id,deleted:false,reason:"worktree_missing"});});
