import {afterEach,expect,test} from "bun:test";import {chmodSync,mkdtempSync,rmSync,writeFileSync} from "node:fs";import {tmpdir} from "node:os";import {join} from "node:path";import {collectEvidence,evidenceReady,type Evidence} from "./evidence";import {defaultCommandExecutor} from "./worktree";
const dirs:string[]=[];afterEach(()=>dirs.splice(0).forEach(d=>rmSync(d,{recursive:true,force:true})));
const base:Evidence={diff:"x",commits:"abc message\n",status:"",checksExitCode:0,checksOutput:"ok",runnerLogTail:""};
test("evidenceReady rejects no changes",()=>expect(evidenceReady({...base,diff:""})).toEqual({ready:false,reason:"no_changes"}));
test("evidenceReady rejects no commits",()=>expect(evidenceReady({...base,commits:""})).toEqual({ready:false,reason:"no_changes"}));
test("evidenceReady rejects dirty worktree",()=>expect(evidenceReady({...base,status:" M x"})).toEqual({ready:false,reason:"dirty_worktree"}));
test("evidenceReady distinguishes missing check",()=>expect(evidenceReady({...base,checksExitCode:null})).toEqual({ready:false,reason:"no_check"}));
test("evidenceReady rejects failed check",()=>expect(evidenceReady({...base,checksExitCode:1})).toEqual({ready:false,reason:"checks_failed"}));
test("evidenceReady accepts complete evidence collected from real git",async()=>{const root=mkdtempSync(join(tmpdir(),"evidence-"));dirs.push(root);const repo=join(root,"repo"),art=join(root,"art");Bun.spawnSync(["git","init",repo]);Bun.spawnSync(["git","-C",repo,"config","user.email","t@e.st"]);Bun.spawnSync(["git","-C",repo,"config","user.name","T"]);writeFileSync(join(repo,"a"),"a");Bun.spawnSync(["git","-C",repo,"add","."]);Bun.spawnSync(["git","-C",repo,"commit","-m","base"]);const baseRef=Bun.spawnSync(["git","-C",repo,"rev-parse","HEAD"]).stdout.toString().trim();writeFileSync(join(repo,"a"),"b");writeFileSync(join(repo,"orchestrator.check"),"#!/bin/sh\necho checked\n");chmodSync(join(repo,"orchestrator.check"),0o755);Bun.spawnSync(["git","-C",repo,"add","."]);Bun.spawnSync(["git","-C",repo,"commit","-m","change"]);const e=await collectEvidence(repo,"t",baseRef,defaultCommandExecutor,art);expect(evidenceReady(e)).toEqual({ready:true});expect(e.checksOutput).toContain("checked");});

test("collectEvidence reports a present but non-executable check as failed, not absent",async()=>{const root=mkdtempSync(join(tmpdir(),"evidence-nonexec-"));dirs.push(root);const repo=join(root,"repo"),art=join(root,"art");Bun.spawnSync(["git","init",repo]);Bun.spawnSync(["git","-C",repo,"config","user.email","t@e.st"]);Bun.spawnSync(["git","-C",repo,"config","user.name","T"]);writeFileSync(join(repo,"a"),"a");Bun.spawnSync(["git","-C",repo,"add","."]);Bun.spawnSync(["git","-C",repo,"commit","-m","base"]);const baseRef=Bun.spawnSync(["git","-C",repo,"rev-parse","HEAD"]).stdout.toString().trim();writeFileSync(join(repo,"a"),"b");writeFileSync(join(repo,"orchestrator.check"),"#!/bin/sh\necho checked\n");chmodSync(join(repo,"orchestrator.check"),0o644);Bun.spawnSync(["git","-C",repo,"add","."]);Bun.spawnSync(["git","-C",repo,"commit","-m","change"]);const evidence=await collectEvidence(repo,"task",baseRef,defaultCommandExecutor,art);expect(evidence.checksExitCode).toBe(1);expect(evidence.checksOutput).not.toBe("");expect(evidenceReady(evidence)).toEqual({ready:false,reason:"checks_failed"});});
