import { afterEach, describe, expect, test } from "bun:test";
import { mkdtempSync, rmSync } from "node:fs"; import { tmpdir } from "node:os"; import { join } from "node:path";
import { addTask, claim, getTask, openStore, transition } from "./store";
const BASE_REF="a".repeat(40);const dirs:string[]=[]; function store(){const d=mkdtempSync(join(tmpdir(),"orch-"));dirs.push(d);return openStore(join(d,"db"));}afterEach(()=>{for(const d of dirs.splice(0))rmSync(d,{recursive:true,force:true});});
describe("orchestrator store",()=>{
 test("claim enforces repo lock while skipping to independent repo",()=>{const db=store();const a=addTask(db,"a","/a",BASE_REF,1),b=addTask(db,"b","/a",BASE_REF,2),c=addTask(db,"c","/b",BASE_REF,3);expect(claim(db,"owner",4,4).map(x=>x.task_id)).toEqual([a.task_id,c.task_id]);expect(getTask(db,b.task_id)?.state).toBe("queued");db.close();});
 test("cap counts only starting and running",()=>{const db=store();const a=addTask(db,"a","/a",BASE_REF,1),b=addTask(db,"b","/b",BASE_REF,2),c=addTask(db,"c","/c",BASE_REF,3);claim(db,"o",2,4);transition(db,a.task_id,"worktree_ok",{},5);transition(db,a.task_id,"runner_exit",{},6);expect(claim(db,"o",2,7).map(x=>x.task_id)).toEqual([c.task_id]);expect(getTask(db,b.task_id)?.state).toBe("starting");db.close();});
 test("illegal event rejected and budgets only documented retries",()=>{const db=store();const t=addTask(db,"a","/a",BASE_REF);expect(()=>transition(db,t.task_id,"ci_merged")).toThrow("Illegal transition");claim(db,"o");expect(transition(db,t.task_id,"bind_timeout").retry_budget).toBe(1);expect(transition(db,t.task_id,"session_bound").retry_budget).toBe(1);expect(transition(db,t.task_id,"runner_dead").retry_budget).toBe(0);expect(transition(db,t.task_id,"spawn_fail").retry_budget).toBe(0);expect(transition(db,t.task_id,"human_reopen").retry_budget).toBe(2);db.close();});
 test("attempt survives close and reopen",()=>{const d=mkdtempSync(join(tmpdir(),"orch-"));dirs.push(d);const p=join(d,"db");let db=openStore(p);const t=addTask(db,"a","/a",BASE_REF);claim(db,"o");const attempt=getTask(db,t.task_id)?.attempt_id;db.close();db=openStore(p);expect(getTask(db,t.task_id)?.attempt_id).toBe(attempt);expect(getTask(db,t.task_id)?.state).toBe("starting");db.close();});
});
