import { Database } from "bun:sqlite";
import { chmodSync, mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { createHash, randomUUID } from "node:crypto";

export const defaultMailboxPath = join(homedir(), ".overload", "orchestrator-answers.db");
export type ConsumerOwner = "extension" | "orchestrator";
export type ApprovalTarget = { consumerOwner:ConsumerOwner; approvalId:string; stableId?:string; requestUid?:string; targetVersion:string; question:string; options:string[]; effect:string; scope:Record<string,unknown>; evidence:Record<string,unknown>; evidenceHash:string; expiresAt:number; state:"active"|"consumed"|"closed"; };
export type Receipt = { receiptId:string; consumerOwner:ConsumerOwner; approvalId:string; targetVersion:string; answer:string; actor:string; attemptId:string|null; consumedAt:number; appliedAt:number|null; outcome:string|null };

export function canonical(value:unknown):string {
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`;
  return `{${Object.keys(value as object).sort().map(k=>`${JSON.stringify(k)}:${canonical((value as any)[k])}`).join(",")}}`;
}
export function digest(value:unknown):string { return createHash("sha256").update(canonical(value)).digest("hex"); }
function columns(db:Database, table:string):Set<string>{return new Set((db.query(`PRAGMA table_info(${table})`).all() as Array<{name:string}>).map(x=>x.name));}
export function openMailbox(path=process.env.OVERLOAD_ANSWERS_PATH ?? defaultMailboxPath):Database {
  mkdirSync(dirname(path),{recursive:true,mode:0o700}); const db=new Database(path,{create:true}); db.exec("PRAGMA busy_timeout=5000; PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL");
  db.exec(`CREATE TABLE IF NOT EXISTS answers(approval_id TEXT PRIMARY KEY, answer TEXT NOT NULL, actor TEXT NOT NULL, at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS approval_targets(consumer_owner TEXT NOT NULL, approval_id TEXT NOT NULL, stable_id TEXT, request_uid TEXT, target_version TEXT NOT NULL, question TEXT NOT NULL, options TEXT NOT NULL, effect TEXT NOT NULL, scope TEXT NOT NULL, evidence TEXT NOT NULL, evidence_hash TEXT NOT NULL, expires_at INTEGER NOT NULL, state TEXT NOT NULL DEFAULT 'active', consumed_at INTEGER, outcome TEXT, PRIMARY KEY(consumer_owner,approval_id));
CREATE TABLE IF NOT EXISTS answer_metadata(approval_id TEXT PRIMARY KEY, consumer_owner TEXT, provenance TEXT);
CREATE TABLE IF NOT EXISTS bot_identity(id INTEGER PRIMARY KEY CHECK(id=1), bot_id TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS bot_control(id INTEGER PRIMARY KEY CHECK(id=1), disabled INTEGER NOT NULL DEFAULT 0, changed_at INTEGER NOT NULL, reason TEXT);
CREATE TABLE IF NOT EXISTS bot_attempts(attempt_id TEXT PRIMARY KEY, bot_id TEXT NOT NULL, consumer_owner TEXT NOT NULL, approval_id TEXT NOT NULL, target_version TEXT NOT NULL, owner_token TEXT NOT NULL, lease_expires_at INTEGER NOT NULL, policy_hash TEXT NOT NULL, evidence_hash TEXT NOT NULL, state TEXT NOT NULL, reason TEXT, started_at INTEGER NOT NULL, finished_at INTEGER);
CREATE UNIQUE INDEX IF NOT EXISTS bot_attempt_once ON bot_attempts(consumer_owner,approval_id,target_version);
CREATE TABLE IF NOT EXISTS bot_proposals(attempt_id TEXT PRIMARY KEY, consumer_owner TEXT NOT NULL, approval_id TEXT NOT NULL, target_version TEXT NOT NULL, action TEXT NOT NULL, answer TEXT, reason TEXT NOT NULL, evidence_refs TEXT NOT NULL, policy_hash TEXT NOT NULL, created_at INTEGER NOT NULL, invalidated_at INTEGER);
CREATE TABLE IF NOT EXISTS decision_receipts(receipt_id TEXT PRIMARY KEY, consumer_owner TEXT NOT NULL, approval_id TEXT NOT NULL, target_version TEXT NOT NULL, answer TEXT NOT NULL, actor TEXT NOT NULL, attempt_id TEXT, consumed_at INTEGER NOT NULL, applied_at INTEGER, outcome TEXT, UNIQUE(consumer_owner,approval_id,target_version));`);
  const c=columns(db,"answers");if(c.has("consumer_owner")){db.exec("INSERT OR IGNORE INTO answer_metadata(approval_id,consumer_owner,provenance) SELECT approval_id,consumer_owner,provenance FROM answers");}
  chmodSync(path,0o600); return db;
}
export function registerTarget(db:Database,input:Omit<ApprovalTarget,"targetVersion"|"evidenceHash"|"state"> & {targetVersion?:string,evidenceHash?:string}):ApprovalTarget {
  const targetVersion=input.targetVersion ?? digest({owner:input.consumerOwner,id:input.approvalId,question:input.question,options:input.options,effect:input.effect,scope:input.scope,evidence:input.evidence,expiresAt:input.expiresAt});
  const evidenceHash=input.evidenceHash ?? digest(input.evidence);
  db.run(`INSERT INTO approval_targets(consumer_owner,approval_id,stable_id,request_uid,target_version,question,options,effect,scope,evidence,evidence_hash,expires_at,state) VALUES(?,?,?,?,?,?,?,?,?,?,?,?, 'active') ON CONFLICT(consumer_owner,approval_id) DO UPDATE SET stable_id=excluded.stable_id,request_uid=excluded.request_uid,target_version=excluded.target_version,question=excluded.question,options=excluded.options,effect=excluded.effect,scope=excluded.scope,evidence=excluded.evidence,evidence_hash=excluded.evidence_hash,expires_at=excluded.expires_at,state=CASE WHEN approval_targets.state='consumed' THEN approval_targets.state ELSE 'active' END`,[input.consumerOwner,input.approvalId,input.stableId??null,input.requestUid??null,targetVersion,input.question,JSON.stringify(input.options),input.effect,canonical(input.scope),canonical(input.evidence),evidenceHash,input.expiresAt]);
  return {...input,targetVersion,evidenceHash,state:"active"};
}
export function getTarget(db:Database,owner:ConsumerOwner,id:string):ApprovalTarget|null { const r=db.query("SELECT * FROM approval_targets WHERE consumer_owner=? AND approval_id=?").get(owner,id) as any; if(!r)return null; return {consumerOwner:r.consumer_owner,approvalId:r.approval_id,stableId:r.stable_id??undefined,requestUid:r.request_uid??undefined,targetVersion:r.target_version,question:r.question,options:JSON.parse(r.options),effect:r.effect,scope:JSON.parse(r.scope),evidence:JSON.parse(r.evidence),evidenceHash:r.evidence_hash,expiresAt:r.expires_at,state:r.state}; }
export function writeHumanAnswer(db:Database, owner:ConsumerOwner,id:string,answer:string,actor="ui",now=Date.now()):{ok:true}|{ok:false;reason:string}{
  return db.transaction(()=>{const target=getTarget(db,owner,id);if(!target||target.state!=="active")return {ok:false,reason:target?.state==="consumed"?"already_consumed":"unknown_target"} as const;if(now>=target.expiresAt)return {ok:false,reason:"expired"} as const;if(!target.options.includes(answer))return {ok:false,reason:"invalid_option"} as const;const prior=db.query("SELECT consumer_owner FROM answer_metadata WHERE approval_id=?").get(id) as any;if(prior&&prior.consumer_owner&&prior.consumer_owner!==owner)return {ok:false,reason:"owner_conflict"} as const;db.run("INSERT INTO answers(approval_id,answer,actor,at) VALUES(?,?,?,?) ON CONFLICT(approval_id) DO UPDATE SET answer=excluded.answer,actor=excluded.actor,at=excluded.at",[id,answer,actor,now]);db.run("INSERT INTO answer_metadata(approval_id,consumer_owner,provenance) VALUES(?,?,'human') ON CONFLICT(approval_id) DO UPDATE SET consumer_owner=excluded.consumer_owner,provenance='human'",[id,owner]);db.run("UPDATE bot_proposals SET invalidated_at=? WHERE consumer_owner=? AND approval_id=? AND invalidated_at IS NULL",[now,owner,id]);return {ok:true} as const;}).immediate();
}
export type ConsumeInput={consumerOwner:ConsumerOwner;approvalId:string;targetVersion:string;policyHash:string;now?:number;liveValid:()=>boolean;policyValid:(target:ApprovalTarget,proposal:{answer:string;policyHash:string}|null)=>boolean};
export function consumeDecision(db:Database,input:ConsumeInput):Receipt|null { const now=input.now??Date.now(); return db.transaction(()=>{
  const target=getTarget(db,input.consumerOwner,input.approvalId); if(!target||target.state!=="active"||target.targetVersion!==input.targetVersion||now>=target.expiresAt||!input.liveValid())return null;
  const human=db.query("SELECT a.answer,a.actor FROM answers a LEFT JOIN answer_metadata m ON m.approval_id=a.approval_id WHERE a.approval_id=? AND (m.consumer_owner=? OR m.consumer_owner IS NULL) LIMIT 1").get(input.approvalId,input.consumerOwner) as any;
  const p=db.query("SELECT p.answer,p.policy_hash,p.attempt_id FROM bot_proposals p JOIN bot_attempts a ON a.attempt_id=p.attempt_id LEFT JOIN bot_control c ON c.id=1 WHERE p.consumer_owner=? AND p.approval_id=? AND p.target_version=? AND p.action='answer' AND p.invalidated_at IS NULL AND a.state='proposed' AND COALESCE(c.disabled,0)=0 ORDER BY p.created_at LIMIT 1").get(input.consumerOwner,input.approvalId,input.targetVersion) as any;
  const proposal=p?{answer:p.answer,policyHash:p.policy_hash}:null; const answer=human?.answer ?? proposal?.answer; const actor=human?.actor ?? (p?"decision-bot":null); if(!answer||!target.options.includes(answer)||(!human&&!input.policyValid(target,proposal)))return null;
  const receiptId=randomUUID(); db.run("INSERT INTO decision_receipts(receipt_id,consumer_owner,approval_id,target_version,answer,actor,attempt_id,consumed_at) VALUES(?,?,?,?,?,?,?,?)",[receiptId,input.consumerOwner,input.approvalId,input.targetVersion,answer,actor,p?.attempt_id??null,now]); db.run("UPDATE approval_targets SET state='consumed',consumed_at=? WHERE consumer_owner=? AND approval_id=? AND state='active'",[now,input.consumerOwner,input.approvalId]); db.run("UPDATE bot_proposals SET invalidated_at=? WHERE consumer_owner=? AND approval_id=? AND invalidated_at IS NULL",[now,input.consumerOwner,input.approvalId]); if(human){db.run("DELETE FROM answers WHERE approval_id=?",input.approvalId);db.run("DELETE FROM answer_metadata WHERE approval_id=?",input.approvalId);} return {receiptId,consumerOwner:input.consumerOwner,approvalId:input.approvalId,targetVersion:input.targetVersion,answer,actor,attemptId:p?.attempt_id??null,consumedAt:now,appliedAt:null,outcome:null};
  }).immediate(); }
export function receipt(db:Database,owner:ConsumerOwner,id:string):Receipt|null { const r=db.query("SELECT * FROM decision_receipts WHERE consumer_owner=? AND approval_id=?").get(owner,id) as any; return r?{receiptId:r.receipt_id,consumerOwner:r.consumer_owner,approvalId:r.approval_id,targetVersion:r.target_version,answer:r.answer,actor:r.actor,attemptId:r.attempt_id,consumedAt:r.consumed_at,appliedAt:r.applied_at,outcome:r.outcome}:null; }
export function markReceipt(db:Database,id:string,outcome:string,now=Date.now()):void{db.run("UPDATE decision_receipts SET applied_at=COALESCE(applied_at,?),outcome=? WHERE receipt_id=?",[now,outcome,id]);}
export function closeTarget(db:Database,owner:ConsumerOwner,id:string,outcome:string):void{db.run("UPDATE approval_targets SET state=CASE WHEN state='consumed' THEN state ELSE 'closed' END,outcome=? WHERE consumer_owner=? AND approval_id=?",[outcome,owner,id]);}
export function setBotDisabled(db:Database,disabled:boolean,reason:string,now=Date.now()):void{db.transaction(()=>{db.run("INSERT INTO bot_control(id,disabled,changed_at,reason) VALUES(1,?,?,?) ON CONFLICT(id) DO UPDATE SET disabled=excluded.disabled,changed_at=excluded.changed_at,reason=excluded.reason",[disabled?1:0,now,reason]);if(disabled)db.run("UPDATE bot_proposals SET invalidated_at=? WHERE invalidated_at IS NULL",now);})();}
export function botDisabled(db:Database):boolean{return !!(db.query("SELECT disabled FROM bot_control WHERE id=1").get() as any)?.disabled;}
