import { cancelTarget } from "./mailbox";
import {expect,test} from "bun:test";import {mkdtempSync,rmSync} from "node:fs";import {tmpdir} from "node:os";import {join} from "node:path";import {botDisabled,consumeDecision,getTarget,markReceipt,observeReceiptEffect,openMailbox,receipt,reconcileOutstandingReceipts,registerTarget,setBotDisabled,writeHumanAnswer} from "./mailbox";
function fixture(){const root=mkdtempSync(join(tmpdir(),"decision-mailbox-")),path=join(root,"mail.db"),db=openMailbox(path),target=registerTarget(db,{consumerOwner:"extension",approvalId:"a",question:"Q",options:["approve","deny"],effect:"push",scope:{gate:"action",cwd:"/repo"},evidence:{command:"git push"},expiresAt:Date.now()+60_000});return{root,path,db,target,close(){db.close();rmSync(root,{recursive:true,force:true});}}}
test("cancelled target rejects late answers and previously queued approval consumption", () => {
  const f = fixture();
  try {
    expect(writeHumanAnswer(f.db, "extension", "a", "approve")).toEqual({ ok: true });
    expect(cancelTarget(f.db, "extension", "a", "stale-version")).toBe(false);
    expect(getTarget(f.db, "extension", "a")?.state).toBe("active");
    expect(cancelTarget(f.db, "extension", "a", f.target.targetVersion)).toBe(true);
    expect(writeHumanAnswer(f.db, "extension", "a", "approve").ok).toBe(false);
    expect(consumeDecision(f.db, { consumerOwner: "extension", approvalId: "a", targetVersion: f.target.targetVersion, policyHash: "p", liveValid: () => true, policyValid: () => true })).toBeNull();
  } finally { f.close(); }
});
test("human answer is accepted before consume and conflicts after consume",()=>{const f=fixture();expect(writeHumanAnswer(f.db,"extension","a","deny")).toEqual({ok:true});const r=consumeDecision(f.db,{consumerOwner:"extension",approvalId:"a",targetVersion:f.target.targetVersion,policyHash:"p",liveValid:()=>true,policyValid:()=>false});expect(r?.answer).toBe("deny");expect(writeHumanAnswer(f.db,"extension","a","approve")).toEqual({ok:false,reason:"already_consumed"});f.close();});
test("human_only rejects bot proposal but consumes valid human answer",()=>{const f=fixture();f.db.run("UPDATE approval_targets SET decision_mode='human_only' WHERE approval_id='a'");f.db.run("INSERT INTO bot_attempts VALUES('try','bot','extension','a',?,'owner',9999999999999,'p',?,'proposed',NULL,1,2)",[f.target.targetVersion,f.target.evidenceHash]);f.db.run("INSERT INTO bot_proposals VALUES('try','extension','a',?,'answer','approve','ok','[]','p',1,NULL,NULL)",f.target.targetVersion);expect(consumeDecision(f.db,{consumerOwner:"extension",approvalId:"a",targetVersion:f.target.targetVersion,policyHash:"p",liveValid:()=>true,contractValid:()=>true,policyValid:()=>true})).toBeNull();expect(writeHumanAnswer(f.db,"extension","a","approve").ok).toBe(true);expect(consumeDecision(f.db,{consumerOwner:"extension",approvalId:"a",targetVersion:f.target.targetVersion,policyHash:"p",liveValid:()=>true,contractValid:()=>true,policyValid:()=>true})?.actor).toBe("ui");f.close();});
test("contract revision invalidation blocks stale consume",()=>{const f=fixture();writeHumanAnswer(f.db,"extension","a","approve");expect(consumeDecision(f.db,{consumerOwner:"extension",approvalId:"a",targetVersion:f.target.targetVersion,policyHash:"p",liveValid:()=>true,contractValid:()=>false,policyValid:()=>true})).toBeNull();f.close();});
test("effect observation is idempotent and outstanding receipts become unknown",()=>{const f=fixture();writeHumanAnswer(f.db,"extension","a","approve",1);const r=consumeDecision(f.db,{consumerOwner:"extension",approvalId:"a",targetVersion:f.target.targetVersion,policyHash:"p",now:2,liveValid:()=>true,policyValid:()=>true})!;expect(observeReceiptEffect(f.db,{receiptId:r.receiptId,toolCallId:"t",state:"succeeded",evidence:{ok:true},observedAt:3})).toBe(true);expect(observeReceiptEffect(f.db,{receiptId:r.receiptId,toolCallId:"t",state:"succeeded",evidence:{ok:true},observedAt:4})).toBe(true);expect(receipt(f.db,"extension","a")?.outcome).toBe("succeeded");expect(reconcileOutstandingReceipts(f.db,5,6)).toBe(0);f.close();});
test("owner-scoped target rejects foreign human and preserves foreign row",()=>{const f=fixture();f.db.run("INSERT INTO answers VALUES('foreign','approve','legacy',1)");expect(writeHumanAnswer(f.db,"orchestrator","a","approve")).toEqual({ok:false,reason:"unknown_target"});expect((f.db.query("SELECT count(*) n FROM answers WHERE approval_id='foreign'").get() as any).n).toBe(1);f.close();});
test("disabled invalidates proposal while takeover remains available",()=>{const f=fixture();f.db.run("INSERT INTO bot_attempts VALUES('try','bot','extension','a',?,'owner',9999999999999,'p',?,'proposed',NULL,1,2)",[f.target.targetVersion,f.target.evidenceHash]);f.db.run("INSERT INTO bot_proposals VALUES('try','extension','a',?,'answer','approve','ok','[]','p',1,NULL,NULL)",f.target.targetVersion);setBotDisabled(f.db,true,"test",3);expect(botDisabled(f.db)).toBe(true);expect(consumeDecision(f.db,{consumerOwner:"extension",approvalId:"a",targetVersion:f.target.targetVersion,policyHash:"p",liveValid:()=>true,policyValid:()=>true})).toBeNull();expect(writeHumanAnswer(f.db,"extension","a","deny","cli",4)).toEqual({ok:true});f.close();});
test("identity data and receipt replay survive reopen",()=>{const f=fixture();writeHumanAnswer(f.db,"extension","a","approve");const first=consumeDecision(f.db,{consumerOwner:"extension",approvalId:"a",targetVersion:f.target.targetVersion,policyHash:"p",liveValid:()=>true,policyValid:()=>false})!;markReceipt(f.db,first.receiptId,"applied");f.db.close();const reopened=openMailbox(f.path);expect(receipt(reopened,"extension","a")).toMatchObject({receiptId:first.receiptId,outcome:"unknown"});expect(getTarget(reopened,"extension","a")?.state).toBe("consumed");reopened.close();rmSync(f.root,{recursive:true,force:true});});
