import {expect,test} from "bun:test";
import {mkdtempSync,rmSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {openMailbox} from "./mailbox";
import {approvePolicyCandidate,enablePolicyCandidate,proposePolicyCandidate,recordPolicyCandidateEvaluation} from "./policy";

test("candidate needs explicit approval and completed observation before enable",()=>{const root=mkdtempSync(join(tmpdir(),"policy-candidate-")),db=openMailbox(join(root,"m.db"));const rule={id:"r",consumer_owner:"extension" as const,gate:"action",effect:"push",answers:["approve"],cwd:"/repo",command:"git push"};const candidate=proposePolicyCandidate(db,rule,1);expect(enablePolicyCandidate(db,candidate.candidateId,2)).toBeNull();expect(approvePolicyCandidate(db,candidate.candidateId,"owner",10,2)).toBe(true);expect(enablePolicyCandidate(db,candidate.candidateId,9)).toBeNull();expect(enablePolicyCandidate(db,candidate.candidateId,10)).toBeNull();for(let i=1;i<=5;i++){const receiptId=`receipt-${i}`;db.run("INSERT INTO decision_receipts(receipt_id,consumer_owner,approval_id,target_version,answer,actor,attempt_id,consumed_at) VALUES(?,?,?,?,?,?,?,?)",[receiptId,"extension",`a-${i}`,`v-${i}`,"approve","human",null,3]);expect(recordPolicyCandidateEvaluation(db,candidate.candidateId,receiptId,true,4+i)).toBe(true);}expect(enablePolicyCandidate(db,candidate.candidateId,10)).toEqual(rule);expect(enablePolicyCandidate(db,candidate.candidateId,11)).toBeNull();db.close();rmSync(root,{recursive:true,force:true});});
test("candidate samples aggregate only for identical exact scope",()=>{const root=mkdtempSync(join(tmpdir(),"policy-candidate-")),db=openMailbox(join(root,"m.db"));const rule={id:"r",consumer_owner:"extension" as const,gate:"action",effect:"push",answers:["approve"],cwd:"/repo",command:"git push"};expect(proposePolicyCandidate(db,rule,1).sampleCount).toBe(0);expect(proposePolicyCandidate(db,rule,2).sampleCount).toBe(0);expect(proposePolicyCandidate(db,{...rule,command:"git push origin main"},3).candidateId).not.toBe(proposePolicyCandidate(db,rule,4).candidateId);db.close();rmSync(root,{recursive:true,force:true});});
